title: Groundwork
email: info@buildgroundwork.com
description: "Totes McGotes"
baseurl: ""
url: "http://buildgroundwork.com"
username: "buildgroundwork"

# Build settings
markdown: kramdown
permalink: pretty

